name: run pytests
on:
  [push,pull_request,workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Test on ${{ matrix.python-version }}-${{ matrix.os }}
    if: >-
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'Build System'))
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: ["3.9", "3.10", "3.11"]
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}   
          cache: 'pip'   
          cache-dependency-path: 'requirements.txt'

      # Removed redundant python3 pip upgrade step for cross-platform compatibility

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install pytest
          pip install -r requirements.txt

      - name: Install package in development mode
        run: |
          pip install -e .

      - name:  pytests
        run: |
          python --version
          pytest tests


  

