name: run pytests
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: ["3.9", "3.10", "3.11"]
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'   
          cache-dependency-path: 'requirements.txt'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install pytest
          pip install -r requirements.txt
      - name: Install package in development mode
        run: |
          # Install without running PostInstallCommand to avoid JDK installation issues in CI
          pip install -e . --no-deps
      - name: Run tests
        run: |
          python --version
          java -version
          pytest tests -v